### ISSUE TITLE
unable to generate auth link, code 403

### ISSUE THREAD

**Issue by dvtate** [PLhery/node-twitter-api-v2#168]
The following snipped gives code 403
```js
    // Make client
    const client = new TwitterApi({
        appKey: process.env.TWIT_API_KEY,
        appSecret: process.env.TWIT_API_SECRET,
    });

    const link = await client.generateAuthLink('http://localhost:8080', /*{ linkMode: 'authorize' } */);
```

```
[tate@archbook bot]$ ts-node auth.ts 

/home/tate/Desktop/bot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:72
        return new types_1.ApiResponseError(errorString, {
               ^
Error: Request failed with code 403
    at RequestHandlerHelper.createResponseError (/home/tate/Desktop/bot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:72:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/tate/Desktop/bot/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:112:25)
    at IncomingMessage.emit (node:events:402:35)
    at IncomingMessage.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by dvtate** [comment]
potentially related to https://github.com/PLhery/node-twitter-api-v2/issues/167
