### ISSUE TITLE
Error when uploading any media: Request failed with code 400 - Bad Authentication data. (Twitter code 215)

### ISSUE THREAD

**Issue by sixskys** [PLhery/node-twitter-api-v2#176]
I am trying to upload media to twitter, but I keep getting the same error of 400, bad authentication data.
I have tried with a local file, and a url (from your example) and both do not work. I have looked at my settings and v1 has both read and write access so I'm not sure why it's failing.

Here's the relevant code:

```js
const twitterClient = new TwitterApi({
    clientSecret: TWITTER_CLIENT_SECRET,
    clientId: TWITTER_CLIENT_ID,
});

const { client: refreshedTwitterClient, refreshToken: newRefreshToken } =
    await twitterClient.refreshOAuth2Token(TWITTER_REFRESH_TOKEN);

const url =
    'https://lh3.googleusercontent.com/4VfZOC8OThInrab3_uxxchH3izmjRqMNFSoxZ5d7LuGBOj0mfa8-4nGopFwHQJkcktfet5Z_Vnc5LIQaGO8N30sBRF0aV3yNH0QapLI';

const binaryData = await new Promise((resolve, reject) => {
    https
        .get(url, (res) => {
            res.setEncoding('binary');
            let data = Buffer.alloc(0);

            res.on('data', (chunk) => {
                data = Buffer.concat([data, Buffer.from(chunk, 'binary')]);
            });
            res.on('end', () => {
                resolve(data);
            });
        })
        .on('error', (e) => {
            reject(e);
        });
});

// use your downloaded image
const mediaId = await twitterClient.v1.uploadMedia(binaryData, { type: 'jpg' });
```
Here's the output with debug flag (removed some of the properties values in case they are sensitive):
```
[POST upload.twitter.com/1.1/media/upload.json] {
  method: 'POST',
  headers: {
    'x-user-agent': 'Node.twitter-api-v2',
    'content-type': 'multipart/form-data; boundary=--------------------------025323135390937234986623',
    'content-length': 523
  },
  timeout: undefined,
  agent: undefined
}
Request body: <Buffer 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 2d 30 32 35 33 32 33 31 33 35 33 39 30 39 33 37 32 33 34 39 38 36 36 ... 473 more bytes>
Request failed with code 400, data: { errors: [ { code: 215, message: 'Bad Authentication data.' } ] }
Response headers: {
  date: 'Mon, 07 Feb 2022 01:17:09 GMT',
  vary: 'Origin',
  server: 'tsa_o',
  'set-cookie': [
    'guest_id_marketing=e',
    'guest_id_ads=e',
    'personalization_id=',
    'guest_id='
  ],
  'content-type': 'application/json; charset=utf-8',
  'cache-control': 'no-cache, no-store, max-age=0',
  'content-length': '62',
  'x-frame-options': 'SAMEORIGIN',
  'x-xss-protection': '1; mode=block',
  'timing-allow-origin': 'https://twitter.com, https://mobile.twitter.com',
  'strict-transport-security': 'max-age=631138519',
  'x-response-time': '103',
  'x-connection-hash': '5',
  connection: 'close'
}
[POST upload.twitter.com/1.1/media/upload.json]: Request succeeds with code 400
Response body: { errors: [ { code: 215, message: 'Bad Authentication data.' } ] }
/home/karizma/code/ravenxi/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:71
        return new types_1.ApiResponseError(errorString, {
               ^

ApiResponseError: Request failed with code 400 - Bad Authentication data. (Twitter code 215)
    at RequestHandlerHelper.createResponseError (/home/karizma/code/ravenxi/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:71:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/karizma/code/ravenxi/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:116:25)
```

**Comment by sixskys** [comment]
Looks like I forgot to use the new refreshed client and instead used the old one.

**Comment by MarkMcKinney** [comment]
Sorry to re-open a closed issue, but I couldn't contact @sixskys directly. I'm implementing the code you've written here and I keep getting a 403 error. Were you able to get media uploads working via V2 API and the refreshOAuth2Token() function?

**Comment by MarkMcKinney** [comment]
> I could not get media uploads with solely v2. I ended up using two clients, one for v1 and one for v2.  v2 for the main application, and v1 for just media uploads. @MarkMcKinney 

Ok makes sense, appreciate your response!
