### ISSUE TITLE
Error client.v2. ZlistMembers function

### ISSUE THREAD

**Issue by ulbqb** [PLhery/node-twitter-api-v2#177]
# My Environment

- Operating System version: MacOS 11.6
- node-twitter-api-v2 version: 1.10.0
- Nodejs version: 14.18.0

# Problem
When I run the Members of a list API, I get the following error.

## minimal code
``` 
'use strict';
const {TwitterApi} = require('twitter-api-v2');
const client = new TwitterApi('hogehoge');

!(async () => {
  try {
    const membersOfList = await client.v2.listMembers('102');
    for await (const user of membersOfList) {
      console.log(user.id);
    }
  } catch (err) {
    console.log(err);
  }
})();
```
## result
```
TypeError: Cannot read property 'next_token' of undefined
    at UserListMembersV2Paginator.canFetchNextPage (./node_modules/twitter-api-v2/dist/paginators/v2.paginator.js:109:30)
    at UserListMembersV2Paginator.[Symbol.asyncIterator] (./node_modules/twitter-api-v2/dist/paginators/TwitterPaginator.js:110:37)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async ./index.js:8:22
```

**Comment by alkihis** [comment]
Hi, thank you for your submission!

I see where things goes wrong in the code.
It happens when data fetched from Twitter is empty (0 results), sometimes Twitter "forgots" to send the `meta` property.

It will be fixed soon :) for now, before entering your loop, ensure that paginator is not empty:
```ts
if (membersOfList.lists.length) {
  ... do for-await of...
}
```

**Comment by ulbqb** [comment]
@alkihis  I was able to run it safely. Thank you.

**Comment by alkihis** [comment]
Definitive fix available in 1.10.1, tell me if it solves the problem in your case.

**Comment by ulbqb** [comment]
@alkihis No problem. Thank you!
