### ISSUE TITLE
Request error: Error: read ETIMEDOUT

### ISSUE THREAD

**Issue by 0xbe1** [PLhery/node-twitter-api-v2#223]
I run into a timeout issue.

Here's my code, where I take TWITTER_API_BEARER_TOKEN from my twitter developer portal.

```typescript
import { TwitterApi, TwitterApiV2Settings } from 'twitter-api-v2';

const twitterClient = new TwitterApi("<TWITTER_API_BEARER_TOKEN>")
const roClient = twitterClient.readOnly;
TwitterApiV2Settings.debug = true;

const username = "jack"
try {
  const user = await roClient.v2.user(username);
  console.log(user)
} catch (error) {
  console.log('Error: ', error)
}
```

What I get.

```
getting user
[GET api.twitter.com/2/users/jack] {
  method: 'GET',
  headers: {
    'x-user-agent': 'Node.twitter-api-v2',
    Authorization: 'Bearer <TWITTER_API_BEARER_TOKEN>',
    'accept-encoding': 'br;q=1.0, gzip;q=0.8, deflate;q=0.5, *;q=0.1'
  },
  timeout: undefined,
  agent: undefined
}
Request error: Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (node:internal/errors:691:14)
    at TLSSocket.onConnectEnd (node:_tls_wrap:1585:19)
    at TLSSocket.emit (node:events:532:35)
    at TLSSocket.emit (node:domain:475:12)
    at endReadableNT (node:internal/streams/readable:1346:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'ECONNRESET',
  path: null,
  host: 'api.twitter.com',
  port: 443,
  localAddress: undefined
}
Error:  ApiRequestError: Request failed.
    at RequestHandlerHelper.createRequestError (/Users/0xbe1/source/0xbe1/ns3/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:53:16)
    at RequestHandlerHelper.requestErrorHandler (/Users/0xbe1/source/0xbe1/ns3/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:191:21)
    at ClientRequest.emit (node:events:520:28)
    at ClientRequest.emit (node:domain:475:12)
    at TLSSocket.socketErrorListener (node:_http_client:442:9)
    at TLSSocket.emit (node:events:520:28)
    at TLSSocket.emit (node:domain:475:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  error: true,
  type: 'request'
}
```

Any help? Thanks!

**Comment by 0xbe1** [comment]
Turns out to be a local network issue. Close
