### ISSUE TITLE
Cannot destructure property 'oauth_token_secret' of 'req.session' as it is undefined.

### ISSUE THREAD

**Issue by shafiqueqadri** [PLhery/node-twitter-api-v2#259]
**Describe the bug**

Cannot destructure property 'oauth_token_secret' of 'req.session' as it is undefined.
```
TypeError: Cannot destructure property 'oauth_token_secret' of 'req.session' as it is undefined.
    at /Users/mshafiqueqadri/myapp/twitter-post/routes/index.js:28:11
    at Layer.handle [as handle_request] (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/mshafiqueqadri/myapp/twitter-post/node_modules/express/lib/router/index.js:47:12)
```
**To Reproduce**
On Authorization, when it's callback the URL, it shows this error.

**Expected behavior**

**Version**
 - Node.js version v15.4.0
 - Lib version 1.11.3
 - OS (especially if you use Windows) Mac OS 12.0.1

**Additional context**

**Comment by alkihis** [comment]
This isn't a bug of this lib. You‘ve mis configured your express server.

**Comment by stephenasuncionDEV** [comment]
I'm getting the same error, and I'm using next.js's serverless functions

```
import type { NextApiRequest, NextApiResponse } from "next";
import { TwitterApi } from "twitter-api-v2";

export default async function handler(
  // eslint-disable-next-line
  req: NextApiRequest & { session: any },
  res: NextApiResponse,
) {
  const { oauth_token, oauth_verifier } = req.query;
  const { oauth_token_secret } = req.session; //error here

  const client = new TwitterApi({
    appKey: process.env.TWITTER_CONSUMER_KEY as string,
    appSecret: process.env.TWITTER_CONSUMER_SECRET as string,
    accessToken: oauth_token as string,
    accessSecret: oauth_token_secret as string,
  });

  const { userId } = await client.login(oauth_verifier as string);

  res.status(200).redirect("/");
}
```
