### ISSUE TITLE
Problem when using "reply" on tweet.v2 

### ISSUE THREAD

**Issue by orangies** [PLhery/node-twitter-api-v2#294]
*Note: For questions about how to use an endpoint, or problems related to Twitter API than the lib itself, please use the GitHub Discussions instead of opening a new issue*.
I am using function **client.v2.tweet()** with OAuth 2.0
everything work fine such as media, text, tagged user, reply_settings

but I have a problem when add **reply** function to my request
I also test on Postman with the same request, it work perfectly but when I'm using this v2.tweet() function. It's not working
It return error 400 bad request

This is my raw request
`{
  text: 'this is message',
  reply: {
    in_reply_to_tweet_id: '1532388453207650304',
    exclude_reply_user_ids: [ '1437665675175084033', '3981942198', '1518887466740387840' ]
  },
  media: {
    media_ids: [ '1532571807965818880' ],
    tagged_user_ids: [ '1437665675175084033' ]
  }
}`
(Note: I stringify json already before tweet)

`const client = new TwitterApi(accessToken);
        const rwClient = client.readWrite;
        const {
            data: createdTweet
        } = await rwClient.v2.tweet(raw);`

here is error message 

`ApiResponseError: Request failed with code 400 - Invalid Request: One or more parameters to your request was invalid. (see https://api.twitter.com/2/problems/invalid-request)
    at RequestHandlerHelper.createResponseError (D:\somz_backup\igbot\schebot\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (D:\somz_backup\igbot\schebot\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:252:25)
    at Gunzip.emit (events.js:375:28)
    at Gunzip.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  error: true,
  type: 'response',
  code: 400,`

I don't know how to do next.

**Comment by orangies** [comment]
it said my text is too long.
so I remove JSON.stringify() function
and it's working now.

Thank you for helping me.
