### ISSUE TITLE
Deleting a Poll always throws error

### ISSUE THREAD

**Issue by hashweather** [PLhery/node-twitter-api-v2#316]
Deleting a regular tweet always work flawlessly. However when I tried deleting a Poll it doesn't work and all I keep getting is the below error message
```


ApiResponseError: Request failed with code 400
2022-06-28T17:11:28.513845+00:00 app[web.1]:     at RequestHandlerHelper.createResponseError (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:107:16)
2022-06-28T17:11:28.513846+00:00 app[web.1]:     at RequestHandlerHelper.onResponseEndHandler (/app/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:203:25)
2022-06-28T17:11:28.513846+00:00 app[web.1]:     at IncomingMessage.emit (events.js:412:35)
2022-06-28T17:11:28.513847+00:00 app[web.1]:     at endReadableNT (internal/streams/readable.js:1334:12)
2022-06-28T17:11:28.513847+00:00 app[web.1]:     at processTicksAndRejections (internal/process/task_queues.js:82:21) {
2022-06-28T17:11:28.513848+00:00 app[web.1]:   error: true,
2022-06-28T17:11:28.513848+00:00 app[web.1]:   type: 'response',
2022-06-28T17:11:28.513848+00:00 app[web.1]:   code: 400,
2022-06-28T17:11:28.513848+00:00 app[web.1]:   headers: {
2022-06-28T17:11:28.513849+00:00 app[web.1]:     'cache-control': 'no-cache, no-store, max-age=0',
2022-06-28T17:11:28.513849+00:00 app[web.1]:     'content-length': '0',
2022-06-28T17:11:28.513849+00:00 app[web.1]:     'x-response-time': '0',
2022-06-28T17:11:28.513850+00:00 app[web.1]:     'x-connection-hash': '048b7badf94848fa5204e290b8de1aee882de063738829931cb6731581654b75',
2022-06-28T17:11:28.513850+00:00 app[web.1]:     date: 'Tue, 28 Jun 2022 17:11:28 GMT',
2022-06-28T17:11:28.513850+00:00 app[web.1]:     server: 'tsa_b',
2022-06-28T17:11:28.513850+00:00 app[web.1]:     connection: 'close'
2022-06-28T17:11:28.513851+00:00 app[web.1]:   },
2022-06-28T17:11:28.513851+00:00 app[web.1]:   rateLimit: undefined,
2022-06-28T17:11:28.513851+00:00 app[web.1]:   data: ''
2022-06-28T17:11:28.513851+00:00 app[web.1]: }
```

Here is the code I used for deleting both regular tweet and a poll

       try {
                await twitterAPIV2Client.v2.deleteTweet(pollId);
            } catch (e) {
                console.log(e);
            }

Is there another way around this? Thank you

**Comment by alkihis** [comment]
Hi,
Can you be more precise please?
"pollId" is the tweet ID containing a poll, or a poll ID itself (ID fetched inside poll entity)?

Can you print the `pollId` variable?

**Comment by hashweather** [comment]
@lkihis By Poll Id I meant the tweet ID.

This was how I created the poll initially

           try {
                  const { data: createdTweet } = await twitterAPIV2Client.v2.tweet(question, {
                    poll: {
                        duration_minutes: Math.floor(poll.duration / 60),
                        options: poll.choices
                    }
                });
                tweetId = createdTweet; //I saved this somewhere in my DB
            } catch (e) {
                console.log(`Error creating Twitter Poll`);
                console.log(e);
            }


So, when trying to delete the poll I grabbed the saved tweetId of the Poll and ran the code below

```
   try {
            await twitterAPIV2Client.v2.deleteTweet(tweetId);
        } catch (e) {
            console.log(e);
        }
```

But all I keep getting is the error I mentioned earlier.

Thanks

**Comment by alkihis** [comment]
I run the following code:

```ts
let tweetId = '';

  try {
    const { data: createdTweet } = await client.v2.tweet('Test sondage API', {
      poll: {
        duration_minutes: 60,
        options: ['Option 1', 'Option 2']
      },
    });
    tweetId = createdTweet.id; // NOTE HERE, the .id
    console.log('tweet', tweetId, 'created', createdTweet.text)
  } catch (e) {
    console.log(`Error creating Twitter Poll`);
    console.log(e);
  }

  try {
    await client.v2.deleteTweet(tweetId);
    console.log('tweet deleted successfully.')
  } catch (e) {
    console.log(e);
  }
```

All went well.
```
tweet 1544716220330557441 created Test sondage API
tweet deleted successfully.
```

It must a configuration issue on your side or a problem with storage of the ID. I'm closing this issue.
