### ISSUE TITLE
[bug] uploadMedia returns 400 with Buffer

### ISSUE THREAD

**Issue by HRK44** [PLhery/node-twitter-api-v2#335]
Here is my code :

```javascript
const imgData = await axios('https://www.adobe.com/express/feature/image/media_16ad2258cac6171d66942b13b8cd4839f0b6be6f3.png', { responseType: 'arraybuffer' });
console.log(imgData.data);
const mediaId = await client.v1.uploadMedia(imgData.data, { mimeType: EUploadMimeType.Png });
 ```

and here is the output with the error : 

```
<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 06 40 00 00 04 d3 08 06 00 00 00 2d 61 fb 63 00 00 00 01 73 52 47 42 00 ae ce 1c e9 00 00 00 04 ... 2722597 more bytes>

ApiResponseError: Request failed with code 400 - Invalid Request: One or more parameters to your request was invalid. (see https://api.twitter.com/2/problems/invalid-request)
    at RequestHandlerHelper.createResponseError (/home/xxx/git/xxx/api/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (/home/xxx/git/xxx/api/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:252:25)
    at Gunzip.emit (node:events:390:28)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
  error: true,
  type: 'response',
  code: 400,
  headers: 
    date: 'Thu, 28 Jul 2022 09:10:46 UTC',
    server: 'tsa_a',
    'set-cookie':
      'guest_id_marketing=v1%xxx; Max-Age=63072000; Expires=Sat, 27 Jul 2024 09:10:46 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id_ads=v1%xxx; Max-Age=63072000; Expires=Sat, 27 Jul 2024 09:10:46 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'personalization_id="v1_/xxx"; Max-Age=63072000; Expires=Sat, 27 Jul 2024 09:10:46 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id=v1%xxx; Max-Age=63072000; Expires=Sat, 27 Jul 2024 09:10:46 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    'api-version': '2.48',
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '207',
    'x-access-level': 'read-write',
    'x-frame-options': 'SAMEORIGIN',
    'content-encoding': 'gzip',
    'x-xss-protection': '0',
    'x-rate-limit-limit': '200',
    'x-rate-limit-reset': '1658999745',
    'content-disposition': 'attachment; filename=json.json',
    'x-content-type-options': 'nosniff',
    'x-rate-limit-remaining': '197',
    'strict-transport-security': 'max-age=631138519',
    'x-response-time': '76',
    'x-connection-hash': 'xxx',
    connection: 'close'
  rateLimit: limit: 200, remaining: 197, reset: 1658999745,
  data: 
    errors: Object
    title: 'Invalid Request',
    detail: 'One or more parameters to your request was invalid.',
    type: 'https://api.twitter.com/2/problems/invalid-request'
```

Any idea why it's returning 400?

**Comment by A-BMT02** [comment]
Did you find out what the solution was ? 
 @HRK44

**Comment by HRK44** [comment]
@A-BMT02 I was using 2 different clients so the media wasn't accessible by client 2, I used the `additionalOwners` field to allow client2 to access the media
