### ISSUE TITLE
No overload matches this call. error using OAuth1.0a

### ISSUE THREAD

**Issue by DumbGameMaker** [PLhery/node-twitter-api-v2#346]
**Describe the bug**
```
index.ts:4:5 - error TS2769: No overload matches this call.
  The last overload gave the following error.
    Argument of type '{ appKey: string; appSecret: string; accesstoken: string; accessSecret: string; }' is not assignable to parameter of type 'TwitterApiBase'.
      Object literal may only specify known properties, and 'appKey' does not exist in type 'TwitterApiBase'.

4     appKey: CSKEY,
      ~~~~~~~~~~~~~

  node_modules/.pnpm/twitter-api-v2@1.12.3/node_modules/twitter-api-v2/dist/client.base.d.ts:76:5
    76     constructor(instance: TwitterApiBase, settings?: Partial<IClientSettings>);
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    The last overload is declared here.


Found 1 error.

```

**To Reproduce**
Please indicate all steps that lead to this bug:
1. Request client setup: OAuth1.0a 
2. code:
```js
import {TwitterApi} from 'twitter-api-v2';
const {CSKEY, CSSECRET, ACCESSKEY, ACCESSSECRET} = process.env;
const userClient = new TwitterApi({
    appKey: CSKEY,
    appSecret: CSSECRET,
    accesstoken: ACCESSKEY,
    accessSecret: ACCESSSECRET
});
const rwClient = userClient.readWrite;
rwClient.v2.tweet('twitter-api-v2 is not very awesome!');
```

**Expected behavior**

`rwClient.v2.tweet()` should make a tweet

**Version**
 - node v18.5.0
 - twitter-api-v2 1.12.3
 - Fedora 36

**Additional context**

I tried using Bun first, and got a different error: (path to cwd replaced with `.`)
```
TypeError: undefined is not an object (evaluating 'globalThis.location.protocol')
      at /bun-vfs/node_modules/https/index.js:2:7325
      at buildRequest (./node_modules/.pnpm/twitter-api-v2@1.12.3/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:327:20)
      at makeRequest (./node_modules/.pnpm/twitter-api-v2@1.12.3/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:352:8)
      at ./node_modules/.pnpm/twitter-api-v2@1.12.3/node_modules/twitter-api-v2/dist/client-mixins/request-maker.mixin.js:64:13
      at ./node_modules/.pnpm/twitter-api-v2@1.12.3/node_modules/twitter-api-v2/dist/client.base.js:132:27
      at ./index.ts:10:0
```

**Comment by DumbGameMaker** [comment]
fixed:
I defined a new variable 'tokens' with type 'TwitterApiTokens':
```ts
const tokens: TwitterApiTokens = {
    appKey: CSKEY as string,
    appSecret: CSSECRET as string,
    accessToken: ACCESSKEY,
    accessSecret: ACCESSSECRET
};
```
then I used that. I still get the error with bun though, and Node complains about invalid consumer tokens
