### ISSUE TITLE
ApiResponseError: Request failed with code 403 [bug], when using v2.like

### ISSUE THREAD

**Issue by gbytes-me** [PLhery/node-twitter-api-v2#376]
**Describe the bug**
ApiResponseError, when 'liking' a specific tweet

**To Reproduce**
    const userInfo = (await refreshedClient.v2.me({ 'user.fields': ['location', 'verified', 'created_at', 'description'] })).data
    const Id = userInfo.id
    console.log("ID: " + userInfo.id)
     await refreshedClient.v2.like(Id,tweet_id)

**Error*

> ApiResponseError: Request failed with code 403
>     at RequestHandlerHelper.createResponseError (/Users//projects//server/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:103:16)
>     at RequestHandlerHelper.onResponseEndHandler (/Users//projects//.server/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:252:25)
>     at IncomingMessage.emit (node:events:525:35)
>     at endReadableNT (node:internal/streams/readable:1359:12)
>     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
>   error: true,
>   type: 'response',
>   code: 403,
>   headers: {
>     perf: '<perf>',
>     'content-type': 'application/problem+json',
>     'cache-control': 'no-cache, no-store, max-age=0',
>     'content-length': '93',
>     'x-transaction-id': '<id>',
>     'x-response-time': '174',
>     'x-connection-hash': '<hash>',
>     date: 'Mon, 26 Sep 2022 06:44:19 GMT',
>     server: 'tsa_k',
>     connection: 'close'
>   },
>   rateLimit: undefined,
>   data: {
>     title: 'Forbidden',
>     type: 'about:blank',
>     status: 403,
>     detail: 'Forbidden'
>   }
> }

**Version**
Node v18.9.0
API 1.12.7
Mac OSX
Elevated access to v1 and v2 api

**Additional context**
was trying to like a tweet on behalf of a authenticated client.

**Comment by gbytes-me** [comment]
Seems this has to do with the scope of the authentication. Make sure to include

>  'like.write' ,'like.read' 

when requesting authentication. 
Closing this issue.
