### ISSUE TITLE
Intermittent error: Request failed[bug]

### ISSUE THREAD

**Issue by kush-mish** [PLhery/node-twitter-api-v2#381]
**Describe the bug**
We are getting an error while making calls to Twitter `Error: Request failed.`

**To Reproduce**
We are authenticating with the 3-legged OAuth 1.0a flow.
The error occurs intermittently while using the `twitterClient.v1.tweet` endpoint. And I am not able to find a pattern yet.
```
Error: Request failed.
    at RequestHandlerHelper.createRequestError (/workspace/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:57:16)
    at RequestHandlerHelper.requestErrorHandler (/workspace/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:216:21)
    at ClientRequest.emit (node:events:513:28)
    at ClientRequest.emit (node:domain:489:12)
    at TLSSocket.socketErrorListener (node:_http_client:481:9)
    at TLSSocket.emit (node:events:513:28)
    at TLSSocket.emit (node:domain:489:12)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Expected behavior**
Should be more comprehensive about the error.

**Version**
 - Node.js version - 16
 - Lib version - ^1.12.7
 - OS - Ubuntu 18.04

**Comment by alkihis** [comment]
A request error is a network fail. This is not a fault of the lib.
