### ISSUE TITLE
403 error when attempting to post

### ISSUE THREAD

**Issue by campgurus** [PLhery/node-twitter-api-v2#500]
*Note: For questions about how to use an endpoint, or problems related to Twitter API than the lib itself, please use the GitHub Discussions instead of opening a new issue*.

Trying to create a Twitter bot in Node.js. Getting a 403 error on the request.

here is the full error trace:

```
ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError (/Users/darius/Code/flumly-bot/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:104:16)
    at RequestHandlerHelper.onResponseEndHandler (/Users/darius/Code/flumly-bot/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:262:25)
    at IncomingMessage.emit (node:events:525:35)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    perf: '7626143928',
    'content-type': 'application/problem+json',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '297',
    'x-transaction-id': '210b23a7a4b6ca3c',
    'x-response-time': '2',
    'x-connection-hash': '5a7ce993b8ccc4f087354980c7c7c510c2ded8b91ab6000756d91ded7cd7c16c',
    date: 'Sun, 15 Oct 2023 11:33:38 GMT',
    server: 'tsa_b',
    connection: 'close'
  },
  rateLimit: undefined,
  data: {
    title: 'Unsupported Authentication',
    detail: 'Authenticating with Unknown is forbidden for this endpoint.  Supported authentication types are [OAuth 1.0a User Context, OAuth 2.0 User Context].',
    type: 'https://api.twitter.com/2/problems/unsupported-authentication',
    status: 403
  }
}
```

here is my client config:
```
const { TwitterApi } = require("twitter-api-v2");

const client = new TwitterApi({
    appKey: process.env.TWITTER_API_KEY,
    appSecret: process.env.TWITTER_API_SECRET,
    accessToken: process.env.TWITTER_ACCESS_TOKEN,
    accessSecret: process.env.TWITTER_ACCESS_SECRET,
});

const bearer = new TwitterApi(process.env.TWITTER_BEARER_TOKEN);

const twitterClient = client.readWrite;
const twitterBearer = bearer.readOnly;

module.exports = { twitterClient, twitterBearer };
```
and index.js

```
require("dotenv").config({ path: __dirname + "/.env" });
const { twitterClient } = require("./twitterClient.js")
const tweet = async () => {
    try {
        await twitterClient.v2.tweet("Hello world!");
    } catch (e) {
        console.log(e)
    }
}

tweet();
```

**Comment by mwilkinson22** [comment]
This often happens when a Twitter App isn't a member of a project. Head to your [projects & apps overview page](https://developer.twitter.com/en/portal/projects-and-apps) - if your app appears under "Standalone Apps" you'll need to create a project and assign the app to it

**Comment by campgurus** [comment]
The App is within a project. screenshot:

<img width="1176" alt="Screenshot 2023-10-20 at 6 05 33 AM" src="https://github.com/PLhery/node-twitter-api-v2/assets/1260659/85ad2ddb-6f7a-40cc-ae86-11bf63c00b48">

**Comment by mwilkinson22** [comment]
Ah sorry - I'm not affiliated with this library but I'd just had that problem myself recently, was a bit of a shot in the dark!

On closer inspection it looks like a basic authentication issue - what happens if you call `twitterClient.v1.verifyCredentials()`?

**Comment by campgurus** [comment]
No worries grateful for the help. Meanwhile, I think I don't have access to v1:

```darius@Dariuss-MBP-2 flumly-bot % node index
ApiResponseError: Request failed with code 403 - Your credentials do not allow access to this resource (Twitter code 37)
    at RequestHandlerHelper.createResponseError (/Users/darius/Code/flumly-bot/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:104:16)
    at RequestHandlerHelper.onResponseEndHandler (/Users/darius/Code/flumly-bot/node_modules/twitter-api-v2/dist/cjs/client-mixins/request-handler.helper.js:262:25)
    at Gunzip.emit (node:events:513:28)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    date: 'Fri, 20 Oct 2023 11:17:20 UTC',
    perf: '7626143928',
    server: 'tsa_b',
    'set-cookie': [
      'guest_id_marketing=v1%3A169780064063369209; Max-Age=63072000; Expires=Sun, 19 Oct 2025 11:17:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id_ads=v1%3A169780064063369209; Max-Age=63072000; Expires=Sun, 19 Oct 2025 11:17:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'personalization_id="v1_kxZM5/LOaZoQG0/8kpgZuQ=="; Max-Age=63072000; Expires=Sun, 19 Oct 2025 11:17:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id=v1%3A169780064063369209; Max-Age=63072000; Expires=Sun, 19 Oct 2025 11:17:20 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    ],
    'content-type': 'application/json;charset=utf-8',
    'cache-control': 'no-cache, no-store, max-age=0',
    'x-transaction-id': 'd3171bde74e8da0b',
    'strict-transport-security': 'max-age=631138519',
    'content-encoding': 'gzip',
    'content-length': '106',
    'x-response-time': '4',
    'x-connection-hash': 'c5163e55a1a73330ff02f2aae694e224e1645f5e29dbd0558c0eb2cb0af76eff',
    connection: 'close'
  },
  rateLimit: undefined,
  data: { errors: [ [Object] ] },
  errors: [
    {
      message: 'Your credentials do not allow access to this resource',
      code: 37
    }
  ]
```

**Comment by sir-kain** [comment]
Facing the same issue here

**Comment by wavecatch2020s** [comment]
I am getting the same error when I try to upload Media.
Did anyone had any success with this error?

**Comment by Prottoy2938** [comment]
same error here

**Comment by solojungle** [comment]
> I am getting the same error when I try to upload Media. Did anyone had any success with this error?

Did you ever figure it out? Having the same issue here 😅

**Comment by cheskoxd** [comment]
> > I am getting the same error when I try to upload Media. Did anyone had any success with this error?
> 
> Did you ever figure it out? Having the same issue here 😅

that makes two of us :(

**Comment by solojungle** [comment]
> > > I am getting the same error when I try to upload Media. Did anyone had any success with this error?
> > 
> > 
> > Did you ever figure it out? Having the same issue here 😅
> 
> that makes two of us :(

@cheskoxd my solution is here!

 https://github.com/PLhery/node-twitter-api-v2/discussions/416#discussioncomment-8684794

**Comment by cheskoxd** [comment]
Thanks!!

**Comment by whenmoon** [comment]
> Facing the same issue here
> 
> **EDIT:** I resolved the issue by configuring the authentication settings and subsequently generating new API and secret keys
> 
> ![image](https://private-user-images.githubusercontent.com/8977909/278823589-d1dcd1b3-9825-4df3-b880-3bea644722ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk4NDUxMDgsIm5iZiI6MTcxOTg0NDgwOCwicGF0aCI6Ii84OTc3OTA5LzI3ODgyMzU4OS1kMWRjZDFiMy05ODI1LTRkZjMtYjg4MC0zYmVhNjQ0NzIyZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MDFUMTQ0MDA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTM2NGM4N2U1Y2NiYjcxYjEwOTkzMjQyNDJjMmRkYTc3ZDBiMzMxMTFhNWFiZjlkYTNjYTgxYjZiY2Y0ZGZkOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.hpyRvR3sIURLCkXuxV_fNs5emtltY0NksHYQ9LMUjo0)

Thanks @sir-kain I was also able to fix this issue simply by regenerating keys.
