### ISSUE TITLE
with cloudflare wrangler:Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by nathan77886** [PLhery/node-twitter-api-v2#533]
I'm using CF's Wrangler framework to develop an API, and when I plug in twitter-api-v2, yarn dev starts with an error message
`
    Uncaught TypeError: globalThis.XMLHttpRequest is not a constructor
    
at null.<anonymous> (index.js:11733:11) in checkTypeSupport
    at null.<anonymous> (index.js:11745:38)
`
Seems to be due to a compatibility issue with node? I don't know if this is a bug or if it will be compatible with cf workers in the future

**Comment by PLhery** [comment]
Indeed, it's a compatibility issue between cloudflare workers and node.

See https://developers.cloudflare.com/workers/runtime-apis/nodejs/http/
