### ISSUE TITLE
Not able to use .post method

### ISSUE THREAD

**Issue by faisalsayed10** [PLhery/node-twitter-api-v2#59]
Hi, I'm trying to upload an image using `twitterApi.post("media/upload.json", { media_data: data });`
but this doesn't seem to be working and i'm getting a vague error in my terminal:

```
ApiRequestError: Request failed.
    at RequestHandlerHelper.createRequestError (/Users/fayd/Projects/Twack/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:41:16)
    at ClientRequest.<anonymous> (/Users/fayd/Projects/Twack/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:98:25)
    at ClientRequest.emit (events.js:375:28)
    at ClientRequest.emit (domain.js:470:12)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:375:28)
    at TLSSocket.emit (domain.js:470:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  error: true,
  type: 'request',
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      error: [Function (anonymous)],
      response: [Function (anonymous)]
    },
    _eventsCount: 2,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    _contentLength: null,
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: false,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: true,
      _SNICallback: null,
      servername: null,
      alpnProtocol: null,
      authorized: false,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 11,
      connecting: false,
      _hadError: true,
      _parent: null,
      _host: 'media',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: [Array],
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: [Circular *1],
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: false,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 512,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: false,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(connect-options)]: [Object]
    },
    _header: 'POST /upload.json HTTP/1.1\r\n' +
      'x-user-agent: Node.twitter-api-v2\r\n' +
      'Authorization: OAuth oauth_consumer_key="faefaefaefaefae%3D",oauth_signature_method="HMAC-SHA1",oauth_timestamp="1629642186",oauth_token="feafeafaefae-faefae",oauth_version="1.0"\r\n' +
      'content-type: application/x-www-form-urlencoded;charset=UTF-8\r\n' +
      'content-length: 2768019\r\n' +
      'Host: media\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/upload.json',
    _ended: false,
    res: null,
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'media',
    protocol: 'https:',
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: true,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'x-user-agent': [Array],
      authorization: [Array],
      'content-type': [Array],
      'content-length': [Array],
      host: [Array]
    }
  },
  requestError: Error: getaddrinfo ENOTFOUND media
      at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:26) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'media'
  }
}
```

I have no idea what's wrong, this also happened with `statuses/destroy` but i fixed it by appending .v1 to post(), but this work-around doesn't seem to be working for this error. Any help is appreciated

**Comment by faisalsayed10** [comment]
for information, when i add `.v1` or `.v2` before `.post()` i get this error:

```
ApiResponseError: Request failed with code 404 - Sorry, that page does not exist (Twitter code 34)
    at RequestHandlerHelper.createResponseError (/Users/fayd/Projects/Twack/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:70:16)
    at IncomingMessage.<anonymous> (/Users/fayd/Projects/Twack/node_modules/twitter-api-v2/dist/client-mixins/request-handler.helper.js:111:33)
    at IncomingMessage.emit (events.js:387:35)
    at IncomingMessage.emit (domain.js:470:12)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  error: true,
  type: 'response',
  code: 404,
  request: <ref *1> ClientRequest { ..... }
```

**Comment by alkihis** [comment]
Hello,

I think you're missing out some key points of the library.

**Unprefixed clients** of the lib (without .v1 or .v2) do **not add any prefix to your request URL**, meaning that you must enter the full URL `https://api.twitter.com/...`. So basically, in your first example, you're try to access `POST media/upload.json` (that is an invalid URL for Node.js, so request fails)

As specified [here](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/basics.md#use-the-versionned-api-clients)
```
Using the versionned client auto-prefix requests with default prefixes (for v1: https://api.twitter.com/1.1/, for v2: https://api.twitter.com/2/, for labs v2: https://api.twitter.com/labs/2/) and gives you access to endpoint-wrapper methods!
```
auto-prefixes are generic for v1 or v2. **But, in your case**, you try to use [media/upload](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload) that use a **different** API prefix (`https://upload.twitter.com/1.1/`), so even with `.v1`, request will fail (its why you received a 404 Not Found).

Two solutions:
- You use the [upload media helper](https://github.com/PLhery/node-twitter-api-v2/blob/master/doc/v1.md#upload-a-picturevideosubtitle-to-twitter), as specified in the documentation
- You use the request helper `.post`, but you specify **the API prefix** (body encoding will be guessed automatically)
```ts
twitterApi.v1.post('media/upload.json', { media_data: data }, { prefix: 'https://upload.twitter.com/1.1/' })
```

**Comment by faisalsayed10** [comment]
thanks for the help!
